/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


import hexlet.code.gendiff.Differ;

class AppTest {
    @Test void generateDiff() throws Exception {
        String file1 = "src/test/__fixtures__/file1.json";
        String file2 = "src/test/__fixtures__/file2.json";

        assertNotNull(Differ.generate(file1, file2), "diff should return smth");
    }
}
