/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

import hexlet.code.gendiff.Parser;
import hexlet.code.gendiff.mappers.JSONFileMapper;
import hexlet.code.gendiff.mappers.YAMLFileMapper;
import hexlet.code.gendiff.utils.FileInfo;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;

import hexlet.code.gendiff.Differ;

class AppTest {
    @Test void generateDiffJson() throws Exception {
        String file1 = "src/test/resources/file1.json";
        String file2 = "src/test/resources/file2.json";
        String expect = """
                        {
                          - follow: false
                            host: hexlet.io
                          - proxy: 123.234.53.22
                          - timeout: 50
                          + timeout: 20
                          + verbose: true
                        }""";

        assertEquals(expect.trim(), Differ.generate(file1, file2, "stylish"));
    }

    @Test void generateDiffJsonPlain() throws Exception {
        String file1 = "src/test/resources/file5.json";
        String file2 = "src/test/resources/file6.json";
        String expect = """
                        Property 'chars2' was updated. From [complex value] to false
                        Property 'checked' was updated. From false to true
                        Property 'default' was updated. From null to [complex value]
                        Property 'id' was updated. From 45 to null
                        Property 'key1' was removed
                        Property 'key2' was added with value: 'value2'
                        Property 'numbers2' was updated. From [complex value] to [complex value]
                        Property 'numbers3' was removed
                        Property 'numbers4' was added with value: [complex value]
                        Property 'obj1' was added with value: [complex value]
                        Property 'setting1' was updated. From 'Some value' to 'Another value'
                        Property 'setting2' was updated. From 200 to 300
                        Property 'setting3' was updated. From true to 'none'
                        """;

        assertEquals(expect.trim(), Differ.generate(file1, file2, "plain"));
    }

    @Test void generateDiffYamlPlain() throws Exception {
        String file1 = "src/test/resources/file7.yaml";
        String file2 = "src/test/resources/file8.yaml";
        String expect = """
                        Property 'chars2' was updated. From [complex value] to false
                        Property 'checked' was updated. From false to true
                        Property 'default' was updated. From null to [complex value]
                        Property 'id' was updated. From 45 to null
                        Property 'key1' was removed
                        Property 'key2' was added with value: 'value2'
                        Property 'nested_object' was updated. From [complex value] to [complex value]
                        Property 'numbers2' was updated. From [complex value] to [complex value]
                        Property 'numbers3' was removed
                        Property 'numbers4' was added with value: [complex value]
                        Property 'obj1' was added with value: [complex value]
                        Property 'setting1' was updated. From 'Some value' to 'Another value'
                        Property 'setting2' was updated. From 200 to 300
                        Property 'setting3' was updated. From true to 'none'
                        """;

        assertEquals(expect.trim(), Differ.generate(file1, file2, "plain"));
    }

    @Test void generateDiffJsonWithNesting() throws Exception {
        String file1 = "src/test/resources/file5.json";
        String file2 = "src/test/resources/file6.json";
        String expect = """
                    {
                        chars1: [a, b, c]
                      - chars2: [d, e, f]
                      + chars2: false
                      - checked: false
                      + checked: true
                      - default: null
                      + default: [value1, value2]
                      - id: 45
                      + id: null
                      - key1: value1
                      + key2: value2
                        numbers1: [1, 2, 3, 4]
                      - numbers2: [2, 3, 4, 5]
                      + numbers2: [22, 33, 44, 55]
                      - numbers3: [3, 4, 5]
                      + numbers4: [4, 5, 6]
                      + obj1: {nestedKey=value, isNested=true}
                      - setting1: Some value
                      + setting1: Another value
                      - setting2: 200
                      + setting2: 300
                      - setting3: true
                      + setting3: none
                    }""";

        assertEquals(expect.trim(), Differ.generate(file1, file2, "stylish"));
    }

    @Test void generateDiffYaml() throws Exception {
        String file1 = "src/test/resources/file3.yaml";
        String file2 = "src/test/resources/file4.yaml";
        String expect = """
                        {
                          - follow: false
                            host: hexlet.io
                          - proxy: 123.234.53.22
                          - timeout: 50
                          + timeout: 20
                          + verbose: true
                        }""";

        assertEquals(expect.trim(), Differ.generate(file1, file2, "stylish"));
    }

    @Test void generateDiffYamlWithNesting() throws Exception {
        String file1 = "src/test/resources/file7.yaml";
        String file2 = "src/test/resources/file8.yaml";
        String expect = """
                    {
                        chars1: [a, b, c]
                      - chars2: [d, e, f]
                      + chars2: false
                      - checked: false
                      + checked: true
                      - default: null
                      + default: [value1, value2]
                      - id: 45
                      + id: null
                      - key1: value1
                      + key2: value2
                      - nested_object: {inner_key=inner_value, deep_nested={level=3, items=[x, y, z]}}
                      + nested_object: {inner_key=modified_value, deep_nested={level=4, new_property=added}}
                        numbers1: [1, 2, 3, 4]
                      - numbers2: [2, 3, 4, 5]
                      + numbers2: [22, 33, 44, 55]
                      - numbers3: [3, 4, 5]
                      + numbers4: [4, 5, 6]
                      + obj1: {nestedKey=value, isNested=true}
                        obj2: {nestedKey=value, isNested=false}
                      - setting1: Some value
                      + setting1: Another value
                      - setting2: 200
                      + setting2: 300
                      - setting3: true
                      + setting3: none
                    }""";
        assertEquals(expect.trim(), Differ.generate(file1, file2, "stylish"));
    }

    @Test void parserJSON() throws Exception {
        String file1 = "src/test/resources/file1.json";

        var parser = new Parser();
        var expect = new HashMap<String, Object>();
        expect.put("host", "hexlet.io");
        expect.put("timeout", 50);
        expect.put("proxy", "123.234.53.22");
        expect.put("follow", false);

        assertEquals(expect, parser.parse(new FileInfo(file1)));

    }

    @Test void parserYAML() throws Exception {
        String file1 = "src/test/resources/file3.yaml";

        var parser = new Parser();
        var expect = new HashMap<String, Object>();
        expect.put("host", "hexlet.io");
        expect.put("timeout", 50);
        expect.put("proxy", "123.234.53.22");
        expect.put("follow", false);

        assertEquals(expect, parser.parse(new FileInfo(file1)));

    }

    @Test void mapJSON() throws Exception {
        String file1 = "src/test/resources/file1.json";
        var fInfo = new FileInfo(file1);

        var mapper = new JSONFileMapper();
        var expect = new HashMap<String, Object>();
        expect.put("host", "hexlet.io");
        expect.put("timeout", 50);
        expect.put("proxy", "123.234.53.22");
        expect.put("follow", false);

        assertEquals(expect, mapper.parse(fInfo.getFilePath()));

    }

    @Test void mapYAML() throws Exception {
        String file1 = "src/test/resources/file3.yaml";
        var fInfo = new FileInfo(file1);

        var mapper = new YAMLFileMapper();
        var expect = new HashMap<String, Object>();
        expect.put("host", "hexlet.io");
        expect.put("timeout", 50);
        expect.put("proxy", "123.234.53.22");
        expect.put("follow", false);

        assertEquals(expect, mapper.parse(fInfo.getFilePath()));

    }

}
