/*
 * This source file was generated by the Gradle 'init' task
 */
package hexlet.code;

import hexlet.code.gendiff.Parser;
import hexlet.code.gendiff.mappers.JSONFileMapper;
import hexlet.code.gendiff.mappers.YAMLFileMapper;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;

import hexlet.code.gendiff.Differ;

import java.nio.file.Paths;

class AppTest {
    @Test void generateDiffJson() throws Exception {
        String file1 = "src/test/resources/file1.json";
        String file2 = "src/test/resources/file2.json";

        assertEquals("""
                        {
                          - follow: false
                            host: hexlet.io
                          - proxy: 123.234.53.22
                          - timeout: 50
                          + timeout: 20
                          + verbose: true
                        }""", Differ.generate(file1, file2));
    }

    @Test void generateDiffYaml() throws Exception {
        String file1 = "src/test/resources/file3.yaml";
        String file2 = "src/test/resources/file4.yaml";

        assertEquals("""
                        {
                          - follow: false
                            host: hexlet.io
                          - proxy: 123.234.53.22
                          - timeout: 50
                          + timeout: 20
                          + verbose: true
                        }""", Differ.generate(file1, file2));
    }

    @Test void parserJSON() throws Exception {
        String file1 = "src/test/resources/file1.json";

        var parser = new Parser();
        var expect = new HashMap<String, Object>();
        expect.put("host", "hexlet.io");
        expect.put("timeout", 50);
        expect.put("proxy", "123.234.53.22");
        expect.put("follow", false);

        assertEquals(expect, parser.parse(Paths.get(file1).toAbsolutePath(), "json"));

    }

    @Test void parserYAML() throws Exception {
        String file1 = "src/test/resources/file3.yaml";

        var parser = new Parser();
        var expect = new HashMap<String, Object>();
        expect.put("host", "hexlet.io");
        expect.put("timeout", 50);
        expect.put("proxy", "123.234.53.22");
        expect.put("follow", false);

        assertEquals(expect, parser.parse(Paths.get(file1).toAbsolutePath(), "yaml"));

    }

    @Test void mapJSON() throws Exception {
        String file1 = "src/test/resources/file1.json";

        var mapper = new JSONFileMapper();
        var expect = new HashMap<String, Object>();
        expect.put("host", "hexlet.io");
        expect.put("timeout", 50);
        expect.put("proxy", "123.234.53.22");
        expect.put("follow", false);

        assertEquals(expect,
                        mapper.parse(Paths.get(file1).toAbsolutePath()));

    }

    @Test void mapYAML() throws Exception {
        String file1 = "src/test/resources/file3.yaml";

        var mapper = new YAMLFileMapper();
        var expect = new HashMap<String, Object>();
        expect.put("host", "hexlet.io");
        expect.put("timeout", 50);
        expect.put("proxy", "123.234.53.22");
        expect.put("follow", false);

        assertEquals(expect, mapper.parse(Paths.get(file1).toAbsolutePath()));

    }

}
